### ISSUE TITLE
Dead links to blocks doc

### ISSUE THREAD

**Issue by Rabidax** [greshake/i3status-rust#1147]
Hi,

Both in the wiki and the news file there are dead links to the doc.
They point to https://github.com/greshake/i3status-rust/blob/master/blocks.md when they should point to https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md

Just thought I'd point it out.

**Comment by ammgws** [comment]
You can send a PR if you want

**Comment by GladOSkar** [comment]
PRs to Wikis aren't possible

**Comment by MaxVerevkin** [comment]
@GladOSkar I'm not sure, but it looks like there is an option to allow it 
![image](https://user-images.githubusercontent.com/34583604/113329159-e92c4e00-9325-11eb-8d2b-a4e6a21d0302.png)

**Comment by ammgws** [comment]
I think only @greshake can change it (or maybe @atheriel as well?)

**Comment by ammgws** [comment]
Links should be working now

**Comment by GladOSkar** [comment]
Wiki link works now but the ones in `NEWS.md` are still incorrect

**Comment by atheriel** [comment]
@ammgws I can't modify the repo's wiki settings either, sorry.

**Comment by GladOSkar** [comment]
I guess that's a matter for @greshake then
